# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.client_voter:
        class: AppBundle\Security\ClientVoter
        tags:
            - {name: security.voter}
        public: false

    #This is for using the entity manager in ReservationType.php
    #It is not used now
    app.constructor:
        class: AppBundle\Form\Type\ReservationType
        arguments: [ '@doctrine.orm.entity_manager']
        tags:
            - {name: form.type}
